### ISSUE TITLE
Bug - HP buffs not applied correctly

### ISSUE THREAD

**Issue by LanceBailey** [GamesByMoonlight/Nosferatu#63]
Description - Collecting a health debuff displays the proper, buffed amount of HP, but upon taking damage the current health resets to the pre-buffed amount

Behavior - Pick up a health buff to get the proper +50% buff and the display shows 300/300 (for example if you're the vampire player).  If you take damage from the skeleton, the amount of current HP then drops to 190, then another -10 hp for each skeleton swing

To Replicate - Start the game from the lobby, find a health buff pickup, then take damage from the skeleton

**Comment by LanceBailey** [comment]
I think it has something to do with the player not properly updating the server when they pick up a buff, so when the server tries to apply damage it applies it based on the status of the player on the server (at the original values), then updates the player with their new health.

**Comment by saporter** [comment]
I think this is fixed.  I didn't test very robustly, but I'm pretty sure it's fixed.  reopen if not.
